name: Build Raspberry Pi Image

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  setup:
    name: Setup Environment
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip wget

      - name: Install Packer
        run: |
          wget https://releases.hashicorp.com/packer/1.9.3/packer_1.9.3_linux_amd64.zip
          unzip packer_1.9.3_linux_amd64.zip
          sudo mv packer /usr/local/bin/

      - name: Install ARM Builder Plugin
        run: |
          mkdir -p ~/.config/packer/plugins/github.com/mkaczanowski/arm
          wget https://github.com/mkaczanowski/packer-builder-arm/releases/download/v1.1.0/packer-builder-arm_1.1.0_linux_amd64.tar.gz
          tar -xvf packer-builder-arm_1.1.0_linux_amd64.tar.gz
          chmod +x packer-builder-arm
          mv packer-builder-arm ~/.config/packer/plugins/github.com/mkaczanowski/arm/

      - name: Validate Packer Template
        run: |
          cd packer
          packer init .
          packer validate .
      
  build:
    name: Manual Build Image
    needs: setup
    runs-on: ubuntu-latest
    
    environment:
      name: prod
    
    steps:
      - name: Build Image
        run: |
          packer build \
            -var "ssh_password=${{ secrets.SSH_PASS }}" \
            -var-file=config/prod.pkrvars.hcl \
            .

      - name: Upload Image Artifact
        uses: actions/upload-artifact@v3
        with:
          name: rpi-ubuntu
          path: packer/build/output/*.img
