name: Build Raspberry Pi Image

on:
  push:
    branches: [ "main", "master", "develop" ]

jobs:
  build-dev:
    name: Manual Build Image (Dev)
    runs-on: ubuntu-latest

    # Dev environment, no manual approval required (unless you add rules for 'dev')
    environment:
      name: dev

    if: ${{ github.ref == 'refs/heads/develop' }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip wget

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup

      - name: Run `packer init`
        id: init
        run: |
          cd packer
          packer init .

      - name: Run `packer validate`
        id: validate
        run: |
          cd packer
          packer validate \
            -var "ssh_private_key=${{ secrets.SSH_PRIVATE_KEY }}" \
            -var "ssh_public_key=${{ secrets.SSH_PUBLIC_KEY }}" \
            -var-file=/config/dev.pkrvars.hcl \
            ./rpi-ubuntu.pkr.hcl

      - name: Build Image with Logging
        run: |
          cd packer
          packer build \
            -var "ssh_private_key=${{ secrets.SSH_PRIVATE_KEY }}" \
            -var "ssh_public_key=${{ secrets.SSH_PUBLIC_KEY }}" \
            -var-file=/config/dev.pkrvars.hcl \
            ./rpi-ubuntu.pkr.hcl

      - name: Cleanup Build Directory
        run: |
          rm -rf packer/build/temp/

      - name: Upload Image Artifact
        uses: actions/upload-artifact@v3
        with:
          name: rpi-ubuntu-${{ github.run_id }}
          path: packer/build/output/*.img

  build-prod:
    name: Manual Build Image (Prod)
    runs-on: ubuntu-latest

    # Prod environment, which can require manual approval if environment rules are set
    environment:
      name: prod

    if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip wget

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup

      - name: Run `packer init`
        id: init
        run: |
          packer init ./packer/packer.pkr.hcl

      - name: Run `packer validate`
        id: validate
        run: |
          packer validate \
            -var "ssh_private_key=${{ secrets.SSH_PRIVATE_KEY }}" \
            -var "ssh_public_key=${{ secrets.SSH_PUBLIC_KEY }}" \
            -var-file=/packer/config/prod.pkrvars.hcl \
            ./packer/rpi-ubuntu.pkr.hcl

      - name: Build Image with Logging
        run: |
          packer build \
            -var "ssh_private_key=${{ secrets.SSH_PRIVATE_KEY }}" \
            -var "ssh_public_key=${{ secrets.SSH_PUBLIC_KEY }}" \
            -var-file=/packer/config/prod.pkrvars.hcl \
            ./packer/rpi-ubuntu.pkr.hcl

      - name: Cleanup Build Directory
        run: |
          rm -rf packer/build/temp/

      - name: Upload Image Artifact
        uses: actions/upload-artifact@v3
        with:
          name: rpi-ubuntu-${{ github.run_id }}
          path: packer/build/output/*.img